name: Go Build and Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }} with Go ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: ['1.20']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Install Dependencies
        run: |
          go get github.com/joho/godotenv
          go get go.mongodb.org/mongo-driver/mongo
      
      - name: Build
        run: go build -v ./
      
      - name: Test
        run: go test -v ./
